#!/bin/bash
# Maintainer: Harenome Ranaivoarivony Razanajato <harno.ranaivo@gmail.com>
# Noob script to backup all the config files listed in list.

function backup_dotfiles()
{
    mkdir -p dotfiles
    while read line
        do cp -r ~/$line dotfiles/
    done < dotfiles_list

    echo "Backup done."
}

function import_dotfiles()
{
    while read line
        do cp -r dotfiles/$line ~/
    done < dotfiles_list

    echo "Dotfiles imported."
}

function ask_both()
{
    echo "Do you want to (B)ackup your dotfiles or (I)mport your saved dotfiles? "
    read whattodo
    case "$whattodo" in
        B | b | backup | Backup | BACKUP ) backup_dotfiles ;;
        I | i | import | Import | IMPORT ) import_dotfiles ;;
        N | n | no | NO ) echo "Why did you run this script then ?!" ;;
        * ) echo "err..." ;;
    esac
}

function ask_backup_only()
{
    echo "Do you want to backup your dotfiles? "
    read yesno
    case "$yesno" in
        Y | y | yes | YES ) backup_dotfiles ;;
        N | n | no | NO ) echo "Why did you run this script then ?!" ;;
        * ) echo "err..." ;;
    esac
}

# First, we need to be in the directory where this script is located
cd "${0%/*}"

# We assume it is the first time if the folder dotfiles does not exist
# If the folder does not exist, there is nothing to import
echo "Did you have a look at the 'dotfiles_list' file? You should answer no to the next question if you did not."
[[ -d dotfiles ]] && ask_both || ask_backup_only

exit 0
