#!/bin/bash
# Maintainer: Harenome Ranaivoarivony Razanajato <harno.ranaivo@gmail.com>
# Noob script to backup all the config files listed in list.
# Last change: November 11th 2012

function backup_dotfiles()
{
    mkdir -p dotfiles
    while read LINE
        do cp -r ~/$LINE dotfiles/
    done < dotfiles_list

    echo "Backup done."
}

function import_dotfiles()
{
    while read LINE
        do cp -r dotfiles/$LINE ~/
    done < dotfiles_list

    echo "Dotfiles imported."
}

function clean_dotfiles()
{
    echo "Are you sure ?"
    read SURE
    case "$SURE" in
        Y | y | yes | Yes | YES ) rm -rf dotfiles ;;
        N | n | no | No | NO ) echo "..." ;;
        *) echo "err..." ;;
    esac
}

function ask_all()
{
    echo "Do you want to (B)ackup your dotfiles, (I)mport your saved dotfiles or (C)lean? "
    read WHATTODO
    case "$WHATTODO" in
        B | b | backup | Backup | BACKUP ) backup_dotfiles ;;
        I | i | import | Import | IMPORT ) import_dotfiles ;;
        C | c | clean | Clean | CLEAN ) clean_dotfiles ;;
        N | n | no | NO ) echo "Why did you run this script then ?!" ;;
        * ) echo "err..." ;;
    esac
}

function ask_backup_only()
{
    echo "Do you want to backup your dotfiles? "
    read YESNO
    case "$YESNO" in
        Y | y | yes | YES ) backup_dotfiles ;;
        N | n | no | NO ) echo "Why did you run this script then ?!" ;;
        * ) echo "err..." ;;
    esac
}

# First, we have to make sure we are in the directory where this script is located
cd "${0%/*}"

# We assume it is the first time if the folder dotfiles does not exist
# If the folder does not exist, there is nothing to import
echo "Did you have a look at the 'dotfiles_list' file? You should answer no to the next question if you did not."
[[ -d dotfiles ]] && ask_all || ask_backup_only

exit 0
