#!/bin/bash
# Little dotfiles manager

## Variables
# Replacing $HOME with another location for the testing stage
TESTHOME=$HOME/tmp

DATE="Feburary 2nd 2013"
VERSION="0.1"

# Dirty (and hopefully, temporary) way to get the full path
DIRNAME="$(pwd)$([[ $(dirname $0) = "." ]] || echo "/$(dirname $0)")"

CONFIGFILE="dotm.rc"
DOBACKUPS=true
OVERWRITELINKS=true
VERBOSE=true

## Functions
function version
{
    echo "dotm, version $VERSION ($DATE)"
}

function help
{
    echo "Usage: ./dotm [OPTIONS]"
}

function backup
{
    cp -r "$1" backups/
}

# Not tested yet
function restore
{
    cp -rf "backups/$1" $TESTHOME/
}

function createlink
{
    # ln has a backup feature, however it is limited
    local TARGET="$DIRNAME/$2"
    local DESTINATION="$TESTHOME/$1"

    if [[ -h "$DESTINATION" ]]; then
        if $VERBOSE; then echo "$DESTINATION is a link to $(readlink $DESTINATION)."; fi
        if $OVERWRITELINKS; then
            if $VERBOSE; then echo "Overwriting the link (New target: $TARGET)."; fi
            ln -sf "$TARGET" "$DESTINATION"
        else
            if $VERBOSE; then echo "Abandonning."; fi
        fi
    elif [[ -e "$DESTINATION" ]]; then
        if $VERBOSE; then echo "$DESTINATION already exists."; fi
        if $DOBACKUPS; then
            if $VERBOSE; then echo "Backuping $DESTINATION."; fi
            backup "$DESTINATION"
            if $VERBOSE; then echo "Creating the symbolic link. $DESTINATION will lead to $TARGET."; fi
            #ln -sf works on regulars files, does not on directories
            rm -r "$DESTINATION"
            ln -s "$TARGET" "$DESTINATION"
        else
            if $VERBOSE; then echo "Abandonning."; fi
        fi
    else
        if $VERBOSE; then echo "Creating the symbolic link. $DESTINATION will lead to $TARGET."; fi
        ln -s "$TARGET" "$DESTINATION"
    fi
}

function checkconfig
{
    local HASERROR=false

    for FILE in $(grep -Env "#|:|^$" $CONFIGFILE | cut -d " " -f 2); do
        [[ ! -e "$FILE" ]] &&
        echo "Error: The file $FILE doesn't exist. Please check your $CONFIGFILE file." &&
        HASERROR=true
    done

    if $HASERROR; then exit 1; fi
}

function singleconfig
{
    BEGINNING=$(grep -n "^$(echo $1):$" $CONFIGFILE | cut -d ':' -f 1)
    awk '{ if (NR > '$BEGINNING') if (length($0) > 0) { print } else { exit } }' $CONFIGFILE | while read DEST TARG; do
        createlink "$DEST" "$TARG"
    done
}

function allconfig
{
    awk '{ if (! match($0,":|#|^$")) { print } }' $CONFIGFILE | while read DEST TARG; do
        createlink "$DEST" "$TARG"
    done
}

function interactive
{
    echo ""
}

## Main
checkconfig
mkdir -p backups

if [[ $# -eq 0 ]]; then
#interactive
    allconfig
else
    singleconfig $1
fi

exit 0
