#!/bin/bash
# Little dotfiles manager

# Variables
DATE="January 28th 2013"
VERSION="0.1"
DIRNAME="$(dirname $0)"

CONFIGFILE="dotm.rc"
DOBACKUPS=true
OVERWRITELINKS=true
VERBOSE=false

# Functions
function version
{
    echo "dotm, version $VERSION ($DATE)"
}

function help
{
    echo "Usage: ./dotm [OPTIONS]"
}

function backup
{
    cp -r "$1" backup/
}

function restore
{
    cp -rf "backup/$1" $HOME/
}

function createlink
{
    # ln has a backup feature, however it is limited
    TARGET="$(echo "$HOME/$1")"
    DESTINATION="$(echo "$DIRNAME/$2")"

    if [[ -h "$DESTINATION" ]]; then
        if $VERBOSE; then echo "$DESTINATION is a link to $(readlink $DESTINATION)."; fi
        if $OVERWRITELINKS; then
            if $VERBOSE; then echo "Overwriting the link."; fi
            ln -sf "$TARGET" "$DESTINATION"
        else
            if $VERBOSE; then echo "Abandonning."; fi
        fi
    elif [[ -e "$DESTINATION" ]]; then
        if $VERBOSE; then echo "$DESTINATION already exists."; fi
        if $DOBACKUPS; then
            if $VERBOSE; then echo "Backuping $DESTINATION."; fi
            backup $DESTINATION
            ln -sf "$TARGET" "$DESTINATION"
        else
            if $VERBOSE; then echo "Abandonning."; fi
        fi
    else
        ln -s "$TARGET" "$DESTINATION"
    fi
}

function singleconfig
{
    BEGINNING=$(grep -n "^$(echo $1):$" $CONFIGFILE | cut -d ':' -f 1)
    for LINE in "$(awk '{ if (NR > '$BEGINNING') if (length($0) > 0) { print } else { exit } }')"; do
        createlink $(echo "$LINE")
    done
}

function allconfig
{
    for LINE in "$(grep -Ev ":|^$" $CONFIGFILE)"; do
        createlink $(echo "$LINE")
    done
}

function interactive
{
}

# Main
mkdir -p backups

if [[ $# -eq 0 ]]; then

else

fi

exit 0
