[options]
    # VIM
    vimcompatible = true
    default_indent = 2
    enable_neomake = false
    tex_conceal = ""
    snippet_engine = 'ultisnips'
    disabled_plugins = ["vim-rooter"]
    vimcompatible = true
    bootstrap_after = "basevim#after"
    # Status line configuration
    statusline_separator = 'slant'
    enable_statusline_mode = true
    enable_statusline_bfpath = true

[[custom_plugins]]
    name = "harenome/vim-mipssyntax"
    merged = false

[[layers]]
    name = "VersionControl"
    enable = false

[[layers]]
    name = "autocomplete"
    enable = false

[[layers]]
    name = "lang#c"
    enable = false
