[options]
    # VIM
    vimcompatible = true
    default_indent = 2
    tex_conceal = ""
    bootstrap_before = "basevim#before"
    bootstrap_after = "basevim#after"

    # Status line configuration
    statusline_separator = 'slant'
    enable_statusline_mode = true
    enable_statusline_bfpath = true

    # Checkers
    enable_neomake = false

    # Annoying project rooter
    disabled_plugins = ["vim-rooter" "projectmanager.vim"]
    project_rooter_automatically = 0
    project_auto_root = false

[[custom_plugins]]
    name = "harenome/vim-mipssyntax"
    merged = false

[[layers]]
    name = "VersionControl"
    enable = false

[[layers]]
    name = "autocomplete"
    enable = false

[[layers]]
    name = "checkers"
    enable = false

[[layers]]
    name = "lang#c"
    enable = true

[[layers]]
    name = "tools"
    enable = true
