[options]
    # VIM
    vimcompatible = true
    default_indent = 2
    tex_conceal = ""
    bootstrap_before = "basevim#before"
    bootstrap_after = "basevim#after"

    # Status line configuration
    statusline_separator = 'arrow'
    enable_statusline_mode = true
    enable_statusline_bfpath = true

    # Checkers
    enable_neomake = false

    # Annoying project rooter
    disabled_plugins = ["vim-rooter" "projectmanager.vim"]
    project_rooter_automatically = 0
    project_auto_root = false

[[custom_plugins]]
    name = "harenome/vim-mipssyntax"
    merged = false

[[layers]]
    name = "ui"
    enable_scrollbar = true

[[layers]]
    name = "tools"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = "autocomplete"

[[layers]]
    name = "checkers"

[[layers]]
    name = "incsearch"

[[layers]]
    name = "gtags"
    gtagslabel = "pygments"

[[layers]]
    name = "treesitter"

[[layers]]
    name = "lang#c"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#latex"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "lang#sh"
