#!/bin/bash
# Command line to attach an unattached tmux session, or start a new one if
# all currently running sessions are already attached.

TMPDIR="$HOME/tmp"
WORKDIR="$HOME/Code"

function launchMainSession
{
    tmux -2 new -d -s "main" -n "admin"
    tmux new-window -t "main" -n "work" -c $WORKDIR
    tmux new-window -t "main" -n "dotfiles" -c "~/.dotfiles"
    tmux new-window -t "main" -n "monitoring" "htop"
    tmux split-window -v "watch --color -d -n 600 \"cdf -h -t ext4\""
    tmux new-window -t "main" -n "misc" -c $TMPDIR
    tmux select-window -t "work"
    tmux -2 attach -t "main"
}

if [[ $# -eq 1 ]] && [[ -d "$1" ]]; then
    WORKDIR="$1"
fi

tmux has -t "main" &&
tmux -2 $(tmux ls | grep -v "(attached)" > /dev/null && echo attach -t $(tmux ls -F "#{session_name} #{?session_attached,(attached),}" | grep -v "(attached)" | head -n 1)) ||
launchMainSession
